name: Stellar Wallet CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
        working-directory: services/stellar-wallet

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
        working-directory: services/stellar-wallet
      - run: bun run lint
        working-directory: services/stellar-wallet

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
        working-directory: services/stellar-wallet
      - run: bun run test
        working-directory: services/stellar-wallet
        env:
          HORIZON_URL: https://horizon-testnet.stellar.org
          SOROBAN_RPC_URL: https://rpc-futura.stellar.org
          PORT: 3001
          ENCRYPTION_KEY: dGVzdC1lbmNyeXB0aW9uLWtleS0zMi1ieXRlcw==
          JWT_SECRET: test-jwt-secret-for-ci

  # Smart contract
  build-smart-contract:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - name: Install Rust target for Soroban
        run: |
          source $HOME/.cargo/env
          rustup target add wasm32v1-none
      - name: Install Stellar CLI with Homebrew
        run: |
          brew update
          brew install stellar-cli
          stellar --version
      - name: Build Cargo project
        run: |
          source $HOME/.cargo/env
          cargo build --verbose
        working-directory: services/stellar-wallet/src/soroban/contracts/kyc-kyb-contract

      - name: Build Soroban contract
        run: |
          source $HOME/.cargo/env
          stellar contract build --verbose
        working-directory: services/stellar-wallet/src/soroban/contracts/kyc-kyb-contract

      - name: Run Cargo tests
        run: |
          source $HOME/.cargo/env
          cargo test --verbose
        working-directory: services/stellar-wallet/src/soroban/contracts/kyc-kyb-contract
